### ISSUE TITLE
Proto contains redundant `player_id` field in `StatusReply.Seeker`

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-java#25]
```proto
message Seeker {
  Physical super = 1;
  string player_id = 2;
  double magnet = 3;
  Vector target = 4;
  double disable_counter = 5;
}
```

`StatusReply.Player` already stores all seeker ids. They should also never change so it is truly redundant.
```proto
message Player {
  string id = 1;
  repeated string seeker_ids = 2;
  string camp_id = 3;
  string name = 4;
  string color = 5;
  int32 score  = 6;
}
```

This should be included in the next iteration of the Seekers protocol.

**Comment by karl-zschiebsch** [comment]
No, this is really important! In Player, you have only a string that refers to the object. It is for faster acces of property informations.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 
I store all my players and seekers in a dictionary together with their ID anyway. Also, I have to convert all these objects to "real" seekers objects. This involves multiple iterations since, for example, I don't just store the player-id in the owner propery of a seeker. I store the whole player object. 

I don't think there is that much of a speed difference. There is just one information in two places.

**Comment by karl-zschiebsch** [comment]
It depends all on how use them. If you only iterate over your seekers, it is faster. If you iterate over all, it is much faster. If you store them in the player, it is currently slower. I have choosen this way, because I only link player and seeker, and not more.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 
https://github.com/seekers-dev/seekers/issues/33

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 

> That is something else and only optimized for speed.

Right, but for the python implemention it makes no difference in speed. For it, it's redundant information. I only need one of the two.

**Comment by karl-zschiebsch** [comment]
With our discussion at math camp, I think we can close this ...
